### ISSUE TITLE
 Create a network using PaaS API returns response with empty nodes

### ISSUE THREAD

**Issue by nitesh7sid** [CryptoCredits/credits-common#8]
I am trying to create a network using PaaS API but the response from the server i am getting is with empty nodes. 

Response:

```
{
    "date_created": "2016-10-20T10:53:00",
    "id": "**********",
    "name": "block-network11",
    "nodes": [],
    "organization_id": "******"
}
```

Am i missing something ?

**Comment by alexykot** [comment]
Hi 

Sorry for delay replyiung, we've been just setting up internal processes and this issue got hanging for a while.

So answering your question - yes, it is normal to get empty list of nodes in the beginning while the network is being bootstrapped. This is because when the network itself is done - the nodes are not yet there and will take a few minutes to be provisioned and come online. However once the nodes are provisioned and healthy - it should come online and be added to the network's `"nodes"` list. 
If that does not happen within around 15 minutes after network creation - there is a problem somewhere in node bootstrapping and you should probably notify us about it.

I hope this answers your question.

Regards,
Alex.

PS: we've created a separate public [credits-paas](https://github.com/CryptoCredits/credits-paas/issues) repo to capture all the PaaS related issues. You can ask further questions there.
